Update

diff --git a/bin/fstab-user b/bin/fstab-user
--- a/bin/fstab-user
+++ b/bin/fstab-user
@@ -1,20 +1,19 @@
 #!/bin/bash
 
-systemctl --user is-enabled fstab-user 2>&1 >/dev/null || {
-  echo "Service is not enabled!";
-  echo "Installation:";
-  echo "ln -sf $(realpath ../../etc/systemd/user/fstab-user.service) /etc/systemd/user/fstab-user.service";
-  echo "systemctl --user enable fstab-user.service";
-  echo "systemctl --user start fstab-user.service";
-  echo;
-  exit;
-}
-
-
-exit
 [ ${EUID} != 0 ] && {
- sudo $0 "$@" || echo "Failed sudo'ong $0";
- exit 0;
+  systemctl --user is-enabled fstab-user 2>&1 >/dev/null || {
+    echo "Service is not enabled!";
+    echo "Installation:";
+    echo "ln -sf $(realpath ../../etc/systemd/user/fstab-user.service) /etc/systemd/user/fstab-user.service";
+    echo "systemctl --user enable fstab-user.service";
+    echo "systemctl --user start fstab-user.service";
+    echo;
+
+    exit 1;
+  }
+
+  sudo $0 "$@" || echo "Failed sudo'ing $0";
+  exit 0;
 }
 
 [ -f /etc/fstab.user/fstab.${SUDO_UID} ] || {
