Update

diff --git a/prototypes/bin/google-chrome-sync b/prototypes/bin/google-chrome-sync
--- a/prototypes/bin/google-chrome-sync
+++ b/prototypes/bin/google-chrome-sync
@@ -14,6 +14,7 @@ function syntax() {
   echo "-pc|--clean	clean target profile-dir deleting unmatched from source"
   echo "-f|--force	creates target directory if not existing"
   echo "-d|--dry-run	dry-run without doing anything"
+  echo "-v|--verbose	show verbose output"
   exit 1
 }
 
@@ -22,11 +23,13 @@ function syntax() {
 declare -i dryRun=0
 declare -i force=0
 declare -i clean=0
+declare -i verbose=0
 declare userDir=~;
+declare browserName='na'
 declare sourceBrowser=''
 declare targetBrowser=''
 
-getopts=`getopt -o t:s:u:fhc --long source:,target:,user:,force,dry-run,clean,help -n "$0" -- "$@"`
+getopts=`getopt -o t:s:u:dfhcv --long source:,target:,user:,force,dry-run,clean,verbose,help -n "$0" -- "$@"`
 
 eval set -- "$getopts"
 while true ; do
@@ -53,6 +56,9 @@ while true ; do
         -d|--dry-run)
 		dryRun=1;
                 shift 1;;
+        -v|--verbose)
+		verbose=1;
+		shift 1;;
         --) shift; break;;
         *|-h|--help)
                 syntax;
@@ -60,39 +66,67 @@ while true ; do
     esac
 done
 
-[ -z "${sourceBrowser}" ] && {
+
+if [ -z "${sourceBrowser}" ];
+then
   echo "Error no source browser given!"
   exit 1
-}
-[ -z "${targetBrowser}" ] && {
+elif [ ! -d "${sourceBrowser}" ];
+then
+  sourceProfileRoot=$(readlink -f "${userDir:-~}/.config/${sourceBrowser}/")
+else
+  sourceProfileRoot=$(realpath "${sourceBrowser}")
+fi
+
+if [ -z "${targetBrowser}" ];
+then
   echo "Error no target browser given!"
   exit 1
-}
+elif [ ! -d "${targetBrowser}" ];
+then
+  targetProfileRoot=$(readlink -f "${userDir:-~}/.config/${targetBrowser}/")
+else
+  targetProfileRoot=$(realpath "${targetBrowser}")
+fi
 
-sourceProfileRoot=$(readlink -f ${userDir:-~}/.config/${sourceBrowser}/)/
-targetProfileRoot=$(readlink -f ${userDir:-~}/.config/${targetBrowser}/)/
-
-[ -d "${sourceProfileRoot}" ] || {
+if [ ! -d "${sourceProfileRoot}" ];
+then
   echo "Error ${sourceProfileRoot} not found!"
   exit 1
-}
+fi
 
-[ -z "${force}" ] && {
-  [ -d "${targetProfileRoot}" ] || {
+if [ -z "${force}" ];
+then
+  if [ ! -d "${targetProfileRoot}" ];
+  then
     echo "Error ${targetProfileRoot} not found! Create directory or use -f"
     exit 1
-  }
-}
+  fi
+fi
 
 declare -a args=()
-declare excludeArg='--exclude='
-declare includeArg=''
+declare logFile="${_pwd}/${_name}.${browserName}.log";
+browserName=$(basename ${sourceProfileRoot});
 
-[ "${dryRun}" ] && args+=(--dry-run)
-[ "${clean}" ] && args+=(--delete --delete-after --delete-excluded)
+if [ "${dryRun}" == 1 ];
+then
+  echo "Running DRY RUN";
+
+ args+=(--dry-run)
+fi
+
+if [ "${clean}" == 1 ];
+then
+ args+=(--delete --delete-after --delete-excluded)
+fi
+
+if [ "${verbose}" == 0 ];
+then
+  args+=( --info=progress2 )
+fi
 
 args+=(--progress)
-args+=(--log-file="${_pwd}/${_name}.log")
+args+=(--log-file="${logFile}")
 args+=(--links --copy-links --copy-dirlinks)
 args+=(--times --prune-empty-dirs)
 
@@ -110,33 +144,42 @@ do
 done
 
 args+=('--filter=merge '${tmpRuleFile}'')
+args+=('--exclude=SingletonCookie' '--exclude=SingletonSocket' '--exclude=SingletonLock' '--exclude="gtk-*/*"')
 
 #args+=('--filter=merge '${syncProfilesDir}'/google-chrome-sync.essential-files.rules')
 #args+=('--filter=merge '${syncProfilesDir}'/google-chrome-sync.no-google-sync.rules')
 #args+=('--filter="- **"')
 
-#  echo rsync -av \
-#    "${args[@]}" \
-#    "${chromeProfileRoot}" "${targetProfileRoot}" \
-#  ;
+#echo rsync -av \
+#  "${args[@]}" \
+#  "${chromeProfileRoot}" "${targetProfileRoot}" \
+#;
+#exit
 
-[ -f "${_pwd}/${_name}.log" ] && {
-  rm "${_pwd}/${_name}.log";
-}
+if [ -f "${logFile}" ];
+then
+  rm -f "${logFile}";
+fi
 
 (
   mkdir -p "${targetProfileRoot}";
   cd "${targetProfileRoot}";
-  rsync -av \
+  rsync -av --progress \
     "${args[@]}" \
     "${sourceProfileRoot}" "${targetProfileRoot}" \
-  || \
-  echo "[error: rsync -av" \
-    "${args[@]}" \
-    "${sourceProfileRoot}" "${targetProfileRoot}" \
-  ;
+  || {
+    echo "[error: rsync -av" \
+      "${args[@]}" \
+      "${sourceProfileRoot}" "${targetProfileRoot}" \
+    ;
+    echo;
+    grep -E 'rsync:|rsync error:' < "${logFile}";
+  }
 )
 
-[ -f "${tmpRuleFile}" ] && rm "${tmpRuleFile}";
+if [ -f "${tmpRuleFile}" ];
+then
+ rm "${tmpRuleFile}";
+fi
 
 exit $?
