Update

diff --git a/usr/local/bin/composer-wrapper b/usr/local/bin/composer-wrapper
--- a/usr/local/bin/composer-wrapper
+++ b/usr/local/bin/composer-wrapper
@@ -1,7 +1,7 @@
 #!/bin/bash
 PWD=$(pwd)
-PHP_BINARY=$(which php7.2 | head -n1);
-COMPOSER_BINARY='composer2.phar';
+PHP_BINARY=$(which php7.2 php7.4 php8.0| head -n1);
+COMPOSER_BINARY=$(which composer2.phar);
 
 echo;
 
@@ -25,16 +25,22 @@ then
 	DESIRED_MAJOR_VERSION=${COMPOSER_PHP_VERSION_ARRAY[0]}.${COMPOSER_PHP_VERSION_ARRAY[1]};
 
 	echo "Searching PHP ${DESIRED_MAJOR_VERSION}";
+	PHP_BINARY=$(ls /usr/bin/php${DESIRED_MAJOR_VERSION}* /usr/local/bin/php${DESIRED_MAJOR_VERSION}* 2> /dev/null | head -n1)
 
-        if [[ $COMPOSER_PHP_VERSION > 7 ]];
-        then
-                PHP_BINARY=$(which php${DESIRED_MAJOR_VERSION} php7 | head -n1);
-        elif [[ $COMPOSER_PHP_VERSION > 5 ]];
-        then
-                PHP_BINARY=$(which php5 php5.6 | head -n1);
-        fi
+	if [[ -z "${PHP_BINARY}" ]];
+	then
+		echo "Error: Unable to find php${DESIRED_MAJOR_VERSION}.* binary!";
+		exit 1;
+	fi
 fi
 
+# Patch Shebang to match desired PHP-Version
+#PHP_VERSION=$(basename ${PHP_BINARY});
+#echo "Patching composer-shebang"
+#sed -i '1!b;s/env php[^\r\n]*/env '${PHP_VERSION}' -d phar.require_hash=false/' ${COMPOSER_BINARY};
+
+update-alternatives --set php ${PHP_BINARY}
+
 echo "Using ${PHP_BINARY} and ${COMPOSER_BINARY}";
-$PHP_BINARY $(dirname $0)/${COMPOSER_BINARY} $@;
+${COMPOSER_BINARY} $@;
 
